esphome:
  name: cat-feeder

esp8266:
  board: d1_mini
  
switch:
  - platform: gpio
    id: catfeeder_motor
    name: "Catfeeder Motor"
    pin: D3
    on_turn_on:
      - delay: 1s
      - wait_until:
          binary_sensor.is_off: catfeeder_stop
      - switch.turn_off: catfeeder_motor

button:
  - platform: template
    name: "Catfeeder"
    id: catfeeder
    icon: "mdi:cat"
    on_press:
      then:
        - switch.turn_on: catfeeder_motor
        - logger.log: "Button pressed"

binary_sensor:
  - platform: gpio
    id: catfeeder_button
    name: "Catfeeder Button"
    device_class: ""
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 1000ms
    on_press:
      then:
        - switch.turn_on: catfeeder_motor
  - platform: gpio
    id: catfeeder_stop
    name: "Catfeeder Stop"
    device_class: "opening"
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms

status_led:
  id: catfeeder_led
  pin:
    number: D4
    inverted: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: "f3a10cdbf9db3e84a516fa29e7b0f034"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cat-Feeder Fallback Hotspot"
    password: "Sn8xo8INGDa4"

captive_portal:

