esphome:
  name: thermostat

esp8266:
  board: d1_mini

i2c:
  sda: D2
  scl: D1

sensor:
  - platform: dht12
    temperature:
      name: "Thermostat Temperature"
      id: therm_temp
    humidity:
      name: "Thermostat Humidity"
    update_interval: 15s

switch:
  - platform: gpio
    id: therm_switch
    name: "Thermostat Switch"
    pin: D3
    restore_mode: ALWAYS_OFF

climate:
  - platform: thermostat
    preset:
    -  name: Your new preset
       default_target_temperature_low: 20.0
    name: "Thermostat"
    min_idle_time: 1s
    min_heating_off_time: 1s
    min_heating_run_time: 1s
    supplemental_heating_action: {}
    supplemental_heating_delta: 0.1
    max_heating_run_time: 5s
    heat_deadband: 0.1
    heat_overrun: 0.1
    sensor: therm_temp
    heat_action:
      - switch.turn_on: therm_switch
    idle_action:
      - switch.turn_off: therm_switch
    visual:
      min_temperature: 18 °C
      max_temperature: 24 °C
      temperature_step: 0.1 °C

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermostat Fallback Hotspot"
    password: "xSDmbjc2z21n"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_pw
