#                                 #
# This is my docker compose file. #
#                                 #

# Networks.
networks:
    vpn-network:
        name: vpn-network
        external: true

# Services.
services:

    # Bazarr
    bazarr:
        container_name: bazarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: lscr.io/linuxserver/bazarr:latest
        networks:
            - vpn-network
        ports:
            - "6767:6767"
        restart: ${US}
        volumes:
            - ${CONFIG}/bazarr:/config
            - /mnt/vd0/data/videos:/media

    # Bitwarden
    bitwarden:
        container_name: bitwarden
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - LOG_FILE=/data/bitwarden.log
            - SIGNUPS_ALLOWED=true
        image: vaultwarden/server:latest
        ports:
            - "8000:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/bitwarden:/data

    # Deluge
    deluge:
        container_name: deluge
        depends_on:
            - gluetun
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - DELUGE_LOGLEVEL=error
        image: lscr.io/linuxserver/deluge:latest
        network_mode: "service:gluetun"
        restart: ${US}
        volumes:
            - ${CONFIG}/deluge:/config
            - /home/${USER}/downloads/deluge:/downloads

    # Frigate
    frigate:
        container_name: frigate
        devices:
            - "/dev/bus/usb:/dev/bus/usb"
            - "/dev/dri/renderD128:/dev/dri/renderD128"
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - FRIGATE_RTSP_PASSWORD=${PW}
        image: ghcr.io/blakeblackshear/frigate:stable
        ports:
            - "5000:5000"
            - "1935:1935"
        privileged: true
        restart: ${US}
        shm_size: "256mb"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG}/frigate:/config
            - /home/${USER}/frigate/storage:/media/frigate
            - type: tmpfs
              target: /tmp/cache
              tmpfs:
                  size: 1000000000

    # Gluetun
    gluetun:
        cap_add:
            - NET_ADMIN
        container_name: gluetun
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - VPN_SERVICE_PROVIDER=nordvpn
            - VPN_TYPE=openvpn
            - OPENVPN_USER=${VPN_USERNAME}
            - OPENVPN_PASSWORD=${VPN_PASSWORD}
            - DOT=on
            - DNS_SERVERS=192.168.1.90,1.1.1.1
            - LOG_LEVEL=info
            - SERVER_COUNTRIES=Netherlands
            - VPN_INPUT_PORTS=8112,6881,58846
        image: qmcgaw/gluetun:latest
        networks:
            - vpn-network
        ports:
            - "8081:8080/tcp"
            - "9091:9091/tcp"
            - "8112:8112" # Deluge
            - "6881:6881" # Deluge
            - "6881:6881/udp" # Deluge
            - "58846:58846" # Deluge
        privileged: true
        restart: ${US}
        sysctls:
            - net.ipv4.ip_forward=1
        volumes:
            - ${CONFIG}/gluetun:/config

    # Grocy
    grocy:
        container_name: grocy
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: lscr.io/linuxserver/grocy
        ports:
            - "9283:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/grocy:/config

    # Ouroboros
    ouroboros:
        container_name: ouroboros
        environment:
            - CLEANUP=true
            - CRON=0 4 * * *
            - LOG_LEVEL=info
            - SELF_UPDATE=true
            - NOTIFIERS=${OUROBOROS_NOTIFIERS}
            - TZ=${TZ}
        image: pyouroboros/ouroboros:latest
        restart: ${US}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    # Plex
    plex:
        container_name: plex
        devices:
            - "/dev/dri:/dev/dri"
        environment:
            - PLEX_UID=${UID}
            - PLEX_GID=${GID}
            - TZ=${TZ}
            - PLEX_CLAIM=${PLEX_CLAIM}
            - VERSION=docker
        image: lscr.io/linuxserver/plex:latest
        ports:
            - "32400:32400"
        restart: ${US}
        volumes:
            - ${CONFIG}/plex:/config
            - /mnt/vd0/data/videos:/data
            - /media/arnold/ssd-data/videos:/arnold-videos
            - /media/arnold/ssd-data/music:/arnold-music

    # Portainer
    portainer:
        command: -H unix:///var/run/docker.sock
        container_name: portainer
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: portainer/portainer-ce:latest
        ports:
            - "9000:9000"
        restart: ${US}
        volumes:
            - ${CONFIG}/portainer:/data
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG}/../shared:/shared
            - /var/run/docker.sock:/var/run/docker.sock

    # Prowlarr
    prowlarr:
        container_name: prowlarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/prowlarr:develop
        networks:
            - vpn-network
        ports:
            - "9696:9696"
        restart: ${US}
        volumes:
            - ${CONFIG}/prowlarr:/config

    # QBittorrentVPN
    qbittorrentvpn:
        container_name: qbittorrentvpn
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - VPN_ENABLED=no
            - VPN_USERNAME=${VPN_USERNAME}
            - VPN_PASSWORD=${VPN_PASSWORD}
            - LAN_NETWORK=192.168.1.0/24
            - NAME_SERVERS=192.168.1.90,1.1.1.1
        image: markusmcnugen/qbittorrentvpn:latest
        networks:
            - vpn-network
        ports:
            - "8080:8080"
            - "8999:8999"
            - "8999:8999/udp"
            - "57437:57437"
        privileged: true
        restart: ${US}
        volumes:
            - ${CONFIG}/qbittorrent:/config
            - /home/${USER}/downloads/qbittorrentvpn:/downloads

    # Radarr
    radarr:
        container_name: radarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: lscr.io/linuxserver/radarr:latest
        networks:
            - vpn-network
        ports:
            - "7878:7878"
        restart: ${US}
        volumes:
            - ${CONFIG}/radarr:/config
            - /mnt/vd0/data/videos:/movies
            - /home/${USER}/downloads/deluge:/downloads

    # Scrutiny
    scrutiny:
        cap_add:
            - SYS_RAWIO
        container_name: scrutiny
        devices:
            - /dev/sda:/dev/sda
            - /dev/sdb:/dev/sdb
            - /dev/sdc:/dev/sdc
            - /dev/sdd:/dev/sdd
            - /dev/sde:/dev/sde
            - /dev/sdf:/dev/sdf
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: ghcr.io/analogj/scrutiny:master-omnibus
        ports:
            - "8088:8080"
            - "8086:8086"
        restart: ${US}
        volumes:
            - ${CONFIG}/scrutiny:/opt/scrutiny/config
            - ${CONFIG}/scrutiny/influxdb2:/opt/scrutiny/influxdb
            - /run/udev:/run/udev:ro

    # Sonarr
    sonarr:
        container_name: sonarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: lscr.io/linuxserver/sonarr:latest
        networks:
            - vpn-network
        ports:
            - "8989:8989"
        restart: ${US}
        volumes:
            - ${CONFIG}/sonarr:/config
            - /mnt/vd0/data/videos:/tv
            - /home/${USER}/downloads/deluge:/downloads

    # Tautulli
    tautulli:
        container_name: tautulli
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
        image: ghcr.io/tautulli/tautulli:latest
        ports:
            - "8182:8181"
        restart: ${US}
        volumes:
            - ${CONFIG}/tautulli:/config
            - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro

    # Tdarr
    tdarr:
        container_name: tdarr
        devices:
            - "/dev/dri:/dev/dri"
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - UMASK_SET=002
            - serverIP=${IP}
            - serverPort=8266
            - webUIPort=8265
            - internalNode=true
            - inContainer=true
            - nodeName=${SERVER}Node
            - ffmpegVersion=6
        image: ghcr.io/haveagitgat/tdarr:latest
        ports:
            - "8265:8265"
            - "8266:8266"
            - "8267:8267"
        restart: ${US}
        volumes:
            - ${CONFIG}/tdarr/server:/app/server
            - ${CONFIG}/tdarr/configs:/app/configs
            - ${CONFIG}/tdarr/logs:/app/logs
            - /mnt/vd0/data:/media
            - ${CONFIG}/../../downloads/tdarr/cache:/temp
