#                                 #
# This is my docker compose file. #
#                                 #

version: "3.9"

# Services.
services:

    # Bazarr
    bazarr:
        container_name: bazarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/bazarr:latest
        ports:
        - "6767:6767"
        restart: ${US}
        volumes:
            - ${CONFIG}/bazarr:/config
            - /mnt/vd0/data/videos/movies:/movies
            - /mnt/vd0/data/videos/series:/tv

    # Bitwarden
    bitwarden:
        container_name: bitwarden
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - LOG_FILE=/data/bitwarden.log
            - SIGNUPS_ALLOWED=true
        image: bitwardenrs/server:latest
        ports:
            - "8000:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/bitwarden:/data

    # Bookstack
    bookstack:
        container_name: bookstack
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - APP_URL=${BKSTCK_APP_URL}
            - DB_HOST=${BKSTCK_DB_HOST}
            - DB_USER=${BKSTCK_DB_USER}
            - DB_PASS=${BKSTCK_DB_PASS}
            - DB_DATABASE=${BKSTCK_DB_DATABASE}
        image: linuxserver/bookstack:latest
        ports:
            - "6875:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/bookstack:/config

    # Firefly
    firefly:
        container_name: firefly
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
            - APP_KEY=${FRFL_APP_KEY}
            - DB_CONNECTION=${FRFL_DB_CONNECTION}
            - DB_HOST=${FRFL_DB_HOST}
            - DB_PORT=${FRFL_DB_PORT}
            - DB_DATABASE=${FRFL_DB_DATABASE}
            - DB_USERNAME=${FRFL_DB_USERNAME}
            - DB_PASSWORD=${FRFL_DB_PASSWORD}
        image: fireflyiii/core:latest
        ports:
            - "8082:8080"
        restart: ${US}
        volumes:
            - ${CONFIG}/firefly/upload:/var/www/html/storage/upload

    #Firefly Data Importer
    firefly-di:
        container_name: firefly-di
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
            - FIREFLY_III_ACCESS_TOKEN=${FRFL_ACCESS_TOKEN}
            - NORDIGEN_ID=${FRFL_NRDGN_ID}
            - NORDIGEN_KEY=${FRFL_NRDGN_KEY}
        image: fireflyiii/data-importer:latest
        ports:
            - "8083:8080"
        restart: ${US}

    # Frigate
    frigate:
        container_name: frigate
        devices:
            # - /dev/bus/usb:/dev/bus/usb # usb coral
            - /dev/dri/renderD128
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PW}
        image: ghcr.io/blakeblackshear/frigate:stable
        ports:
            - "5000:5000"
            - "1935:1935"
        privileged: true
        restart: ${US}
        shm_size: "64mb"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG}/frigate/config.yml:/config/config.yml
            - /home/alex/frigate/storage:/media/frigate

    # Gitea
    gitea:
        container_name: gitea
        environment:
            - USER_UID=${UID}
            - USER_GID=${GID}
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - DB_TYPE=${GITEA_DB_TYPE}
            - DB_HOST=${GITEA_DB_HOST}
            - DB_NAME=${GITEA_DB_DATABASE}
            - DB_USER=${GITEA_DB_USERNAME}
            - DB_PASSWD=${GITEA_DB_PASSWORD}
        image: gitea/gitea:latest
        ports:
            - "3000:3000"
            - "222:22"
        restart: ${US}
        volumes:
            - ${CONFIG}/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
    
    # Grocy
    grocy:
        container_name: grocy
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/grocy
        ports:
            - "9283:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/grocy:/config

    # Homer
    homer:
        container_name: homer
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
        image: b4bz/homer:latest
        ports:
            - "9009:8080"
        restart: ${US}
        volumes:
            - ${CONFIG}/homer/assets:/www/assets
    
    # MotionEye
    motioneye:
        container_name: motioneye
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TIMEZONE=${TZ}
        hostname: motioneye
        image: jshridha/motioneye:latest
        ports:
            - "8765:8765"
        restart: ${US}
        volumes:
            - ${CONFIG}/motioneye:/config

    # Nextcloud
    nextcloud:
        container_name: nextcloud
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
            - MYSQL_PASSWORD=${NXTCLD_DB_PW}
            - MYSQL_DATABASE=${NXTCLD_DB_NAME}
            - MYSQL_USER=${NXTCLD_DB_U}
            - MYSQL_HOST=${NXTCLD_DB_HOST}
            - NEXTCLOUD_ADMIN_USER=${NXTCLD_A_U}
            - NEXTCLOUD_ADMIN_PASSWORD=${NXTCLD_A_PW}
            - REDIS_HOST=${NXTCLD_REDIS_HOST}
        image: linuxserver/nextcloud:26.0.2-ls246
        ports:
            - "3333:443"
        restart: ${US}
        volumes:
            - ${CONFIG}/nextcloud:/config
            - /media/nextcloud/data:/data
            - /mnt/vd0/data/nextcloud:/mrgrfsdata

    # Nginx proxy manager
    nginx-proxy-manager:
        container_name: nginx-proxy-manager
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
            - DB_MYSQL_HOST=${NPM_DB_HOST}
            - DB_MYSQL_PORT=${NPM_DB_PORT}
            - DB_MYSQL_USER=${NPM_DB_USER}
            - DB_MYSQL_PASSWORD=${NPM_DB_PW}
            - DB_MYSQL_NAME=${NPM_DB_NAME}
        image: jc21/nginx-proxy-manager:latest
        ports:
            - "8181:81"
            - "8081:80"
            - "4443:443"
        restart: ${US}
        volumes:
            - ${CONFIG}/nginx-proxy-manager/config:/app/config
            - ${CONFIG}/nginx-proxy-manager/data:/data
            - ${CONFIG}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

    # Ouroboros
    ouroboros:
        container_name: ouroboros
        environment:
            - CLEANUP=true
            - CRON=0 4 * * *
            - LOG_LEVEL=info
            - SELF_UPDATE=true
            - IGNORE=mariadb
            - NOTIFIERS=${OUROBOROS_NOTIFIERS}
            - TZ=${TZ}
        image: pyouroboros/ouroboros:latest
        restart: ${US}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    #Paperless NGX
    # paperless-ngx:
    #     container_name: paperless-ngx
    #     environment:
    #         - PUID=${UID}
    #         - PGID=${GID}
    #         - TZ=${TZ}
    #         - PAPERLESS_REDIS=${PPRLSS_REDIS}
    #         # - PAPERLESS_DBHOST=mariadb
    #         - USERMAP_UID=${UID}
    #         - USERMAP_GID=${GID}
    #         - PAPERLESS_TIME_ZONE=${TZ}
    #         - PAPERLESS_DBUSER=${PPRLSS_DB_USER}
    #         - PAPERLESS_DBPASS=${PPRLSS_DB_PW}
    #         - PAPERLESS_SECRET_KEY=${PPRLSS_SECRET_KEY}
    #         - PAPERLESS_AUTO_LOGIN_USERNAME=${PPRLSS_AUTO_LOGIN_USERNAME}
    #         - PAPERLESS_ADMIN_USER=${PPRLSS_ADMIN_USER}
    #         - PAPERLESS_ADMIN_MAIL=${PPRLSS_ADMIN_MAIL}
    #         - PAPERLESS_ADMIN_PASSWORD=${PPRLSS_ADMIN_PW}
    #         # - PAPERLESS_OCR_LANGUAGE=nld
    #         # - PAPERLESS_OCR_LANGUAGES=eng
    #         # - PAPERLESS_CONVERT_MEMORY_LIMIT=128
    #         # - PAPERLESS_OPTIMIZE_THUMBNAILS=false
    #         # - PAPERLESS_WEBSERVER_WORKERS=1
    #         # - PAPERLESS_OCR_THREADS=1
    #         # - PAPERLESS_TASK_WORKERS=1
    #         # - PAPERLESS_THREADS_PER_WORKER=1
    #         # - PAPERLESS_OCR_CLEAN=none
    #         # - PAPERLESS_OCR_PAGES=2
    #     image: ghcr.io/paperless-ngx/paperless-ngx:latest
    #     ports:
    #         - "8010:8000"
    #     restart: ${US}
    #     volumes:
    #         - ${CONFIG}/paperless-ngx/data:/usr/src/paperless/data
    #         - ${CONFIG}/paperless-ngx/media:/usr/src/paperless/media
    #         - ${CONFIG}/paperless-ngx/export:/usr/src/paperless/export
    #         - ${CONFIG}/paperless-ngx/consume:/usr/src/paperless/consume

    # Plex
    plex:
        container_name: plex
        devices:
            - "/dev/dri:/dev/dri"
        environment:
            - ADVERTISE_IP=http://192.168.1.111:32400/
            - PLEX_UID=${UID}
            - PLEX_GID=${GID}
            - TZ=${TZ}
            - PLEX_CLAIM=${PLEX_CLAIM}
            - NVIDIA_DRIVER_CAPIBILITIES=compute,video,utility
            - NVIDIA_VISIBLE_DEVICES=all
        image: plexinc/pms-docker:latest
        ports:
            - "32400:32400"
        restart: ${US}
        volumes:
            - ${CONFIG}/plex:/config
            - /home/alex/downloads/plex/transcode:/transcode
            - /mnt/vd0/data/videos:/data
        
    # Photoprism
    photoprism:
        container_name: photoprism
        devices:
            - "/dev/dri/renderD128:/dev/dri/renderD128"
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - PHOTOPRISM_ADMIN_PASSWORD=${PHOTO_ADMIN_PW}
            - PHOTOPRISM_ORIGINALS_LIMIT=00
            - PHOTOPRISM_HTTP_COMPRESSION=gzip
            - PHOTOPRISM_DEBUG=false
            - PHOTOPRISM_PUBLIC=false
            - PHOTOPRISM_READONLY=false
            - PHOTOPRISM_EXPERIMENTAL=false
            - PHOTOPRISM_DISABLE_CHOWN=false
            - PHOTOPRISM_DISABLE_WEBDAV=false
            - PHOTOPRISM_DISABLE_SETTINGS=false
            - PHOTOPRISM_DISABLE_TENSORFLOW=false
            - PHOTOPRISM_DISABLE_FACES=false
            - PHOTOPRISM_DISABLE_CLASSIFICATION=false
            - PHOTOPRISM_DARKTABLE_PRESETS=false
            - PHOTOPRISM_DETECT_NSFW=true
            - PHOTOPRISM_UPLOAD_NSFW=true
            - PHOTOPRISM_DATABASE_DRIVER=mysql
            - PHOTOPRISM_DATABASE_SERVER=${PHOTO_DB_HOST}
            - PHOTOPRISM_DATABASE_NAME=${PHOTO_DB_NAME}
            - PHOTOPRISM_DATABASE_USER=${PHOTO_DB_U}
            - PHOTOPRISM_DATABASE_PASSWORD=${PHOTO_DB_PW}
            - PHOTOPRISM_SITE_URL=http://192.168.1.111:2342/
            - PHOTOPRISM_SITE_TITLE=PhotoPrism
            - PHOTOPRISM_SITE_CAPTION=Browse Your Life
            - PHOTOPRISM_SITE_DESCRIPTION=Fotoooo's
            - PHOTOPRISM_SITE_AUTHOR=Alex de Wekker
            - PHOTOPRISM_UID=${UID}
            - PHOTOPRISM_GID=${GID}
            - PHOTOPRISM_UMASK=0000
            - PHOTOPRISM_INIT=tensorflow-amd64-avx2
            - PHOTOPRISM_FFMPEG_BUFFERS=64
            - PHOTOPRISM_FFMPEG_BITRATE=64
            - PHOTOPRISM_FFMPEG_ENCODER=h264_qsv
            - PHOTOPRISM_INIT=intel-graphics tensorflow-amd64-avx2
            - HOME=/mnt/vd0/data/nextcloud/Photos/photoprism
        image: photoprism/photoprism:latest
        restart: ${US}
        ports:
            - "2342:2342"
        volumes:
            - "/mnt/vd0/data/nextcloud/Photos/other:/photoprism/originals/other"
            - "/media/nextcloud/data/woekoe/files/InstantUpload:/photoprism/originals/nextcloud"
            - "${CONFIG}/photoprism:/photoprism/storage"
        working_dir: "/mnt/vd0/data/nextcloud/Photos/photoprism"
 
    # Portainer
    portainer:
        command: -H unix:///var/run/docker.sock
        container_name: portainer
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: portainer/portainer-ce:latest
        ports:
            - "9000:9000"
        restart: ${US}
        volumes:
            - ${CONFIG}/portainer:/data
            - /etc/localtime:/etc/localtime:ro
            - /home/alex/.docker/shared:/shared
            - /var/run/docker.sock:/var/run/docker.sock

    # Prowlarr
    prowlarr:
        container_name: prowlarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/prowlarr:develop
        ports:
            - "9696:9696"
        restart: ${US}
        volumes:
            - ${CONFIG}/prowlarr:/config

    # QBittorrentVPN
    qbittorrentvpn:
        container_name: qbittorrentvpn
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - VPN_ENABLED=yes
            - VPN_USERNAME=${VPN_USERNAME}
            - VPN_PASSWORD=${VPN_PASSWORD}
            - LAN_NETWORK=192.168.1.0/24
            - NAME_SERVERS=192.168.1.90,1.1.1.1
        image: markusmcnugen/qbittorrentvpn:latest
        ports:
            - "8080:8080"
            - "8999:8999"
            - "8999:8999/udp"
        privileged: true
        restart: ${US}
        volumes:
            - ${CONFIG}/qbittorrent:/config
            - /home/alex/downloads/qbittorrentvpn:/downloads

    # Radarr
    radarr:
        container_name: radarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/radarr:nightly
        ports:
            - "7878:7878"
        restart: ${US}
        volumes:
            - ${CONFIG}/radarr:/config
            - /mnt/vd0/data/videos:/movies
            - /home/alex/downloads/qbittorrentvpn:/downloads

    # Scrutiny
    scrutiny:
        cap_add:
            - SYS_RAWIO
        container_name: scrutiny
        devices:
            - /dev/sda:/dev/sda
            - /dev/sdb:/dev/sdb
            - /dev/sdc:/dev/sdc
            - /dev/sdd:/dev/sdd
            - /dev/sde:/dev/sde
            - /dev/sdf:/dev/sdf
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: ghcr.io/analogj/scrutiny:master-omnibus
        ports:
            - "8088:8080"
            - "8086:8086"
        restart: ${US}
        volumes:
            - ${CONFIG}/scrutiny:/opt/scrutiny/config
            - ${CONFIG}/scrutiny/influxdb2:/opt/scrutiny/influxdb
            - /run/udev:/run/udev:ro

    # Sonarr
    sonarr:
        container_name: sonarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/sonarr:latest
        ports:
            - "8989:8989"
        restart: ${US}
        volumes:
            - ${CONFIG}/sonarr:/config
            - /mnt/vd0/data/videos:/tv
            - /home/alex/downloads/qbittorrentvpn:/downloads

    # Tautulli
    tautulli:
        container_name: tautulli
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
        image: tautulli/tautulli:latest
        ports:
            - "8182:8181"
        restart: ${US}
        volumes:
            - ${CONFIG}/tautulli:/config
            - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
    
    # Tdarr
    tdarr:
        container_name: tdarr
        devices:
            - "/dev/dri:/dev/dri"
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - serverIP=192.168.1.111
            - serverPort=8266
            - webUIPort=8265
            - internalNode=true
            - nodeID=SergeNode
        image: haveagitgat/tdarr:latest
        ports:
            - "8265:8265"
            - "8266:8266"
            - "8267:8267"
        restart: ${US}
        volumes:
            - ${CONFIG}/tdarr/server:/app/server
            - ${CONFIG}/tdarr/configs:/app/configs
            - ${CONFIG}/tdarr/logs:/app/logs
            - /mnt/vd0/data:/media
            - ${CONFIG}/../../downloads/tdarr/cache:/temp
