#                                 #
# This is my docker compose file. #
#                                 #

version: "3.9"

# Services.
services:

    # Bazarr
    bazarr:
        container_name: bazarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/bazarr:latest
        ports:
            - "6767:6767"
        restart: ${US}
        volumes:
            - ${CONFIG}/bazarr:/config
            - /mnt/vd0/data/videos/movies:/movies
            - /mnt/vd0/data/videos/series:/tv

    # Bitwarden
    bitwarden:
        container_name: bitwarden
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - LOG_FILE=/data/bitwarden.log
            - SIGNUPS_ALLOWED=true
        image: vaultwarden/server:latest
        ports:
            - "8000:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/bitwarden:/data

    # Frigate
    frigate:
        container_name: frigate
        devices:
            - "/dev/apex_0:/dev/apex_0"
            - "/dev/dri:/dev/dri"
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - FRIGATE_RTSP_PASSWORD=${PW}
        image: ghcr.io/blakeblackshear/frigate:stable
        ports:
            - "5000:5000"
            - "1935:1935"
        privileged: true
        restart: ${US}
        shm_size: "128mb"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG}/frigate/config.yml:/config/config.yml
            - /home/${USER}/frigate/storage:/media/frigate

    # Grocy
    grocy:
        container_name: grocy
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/grocy
        ports:
            - "9283:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/grocy:/config

    # Ouroboros
    ouroboros:
        container_name: ouroboros
        environment:
            - CLEANUP=true
            - CRON=0 4 * * *
            - LOG_LEVEL=info
            - SELF_UPDATE=true
            - NOTIFIERS=${OUROBOROS_NOTIFIERS}
            - TZ=${TZ}
        image: pyouroboros/ouroboros:latest
        restart: ${US}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    # Plex
    plex:
        container_name: plex
        devices:
            - "/dev/dri:/dev/dri"
        environment:
            - PLEX_UID=${UID}
            - PLEX_GID=${GID}
            - TZ=${TZ}
            - PLEX_CLAIM=${PLEX_CLAIM}
            - VERSION=docker
        image: lscr.io/linuxserver/plex:latest
        ports:
            - "32400:32400"
        restart: ${US}
        volumes:
            - ${CONFIG}/plex:/config
            - /mnt/vd0/data/videos:/data
            - /media/arnold/ssd-data/videos:/arnold-videos
            - /media/arnold/ssd-data/music:/arnold-music

    # Portainer
    portainer:
        command: -H unix:///var/run/docker.sock
        container_name: portainer
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: portainer/portainer-ce:latest
        ports:
            - "9000:9000"
        restart: ${US}
        volumes:
            - ${CONFIG}/portainer:/data
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG}/../shared:/shared
            - /var/run/docker.sock:/var/run/docker.sock

    # Prowlarr
    prowlarr:
        container_name: prowlarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/prowlarr:develop
        ports:
            - "9696:9696"
        restart: ${US}
        volumes:
            - ${CONFIG}/prowlarr:/config

    # QBittorrentVPN
    qbittorrentvpn:
        container_name: qbittorrentvpn
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - VPN_ENABLED=yes
            - VPN_USERNAME=${VPN_USERNAME}
            - VPN_PASSWORD=${VPN_PASSWORD}
            - LAN_NETWORK=192.168.1.0/24
            - NAME_SERVERS=192.168.1.90,1.1.1.1
        image: markusmcnugen/qbittorrentvpn:latest
        ports:
            - "8080:8080"
            - "8999:8999"
            - "8999:8999/udp"
        privileged: true
        restart: ${US}
        volumes:
            - ${CONFIG}/qbittorrent:/config
            - /home/${USER}/downloads/qbittorrentvpn:/downloads

    # Radarr
    radarr:
        container_name: radarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/radarr:nightly
        ports:
            - "7878:7878"
        restart: ${US}
        volumes:
            - ${CONFIG}/radarr:/config
            - /mnt/vd0/data/videos:/movies
            - /home/${USER}/downloads/qbittorrentvpn:/downloads

    # Scrutiny
    scrutiny:
        cap_add:
            - SYS_RAWIO
        container_name: scrutiny
        devices:
            - /dev/sda:/dev/sda
            - /dev/sdb:/dev/sdb
            - /dev/sdc:/dev/sdc
            - /dev/sdd:/dev/sdd
            - /dev/sde:/dev/sde
            - /dev/sdf:/dev/sdf
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: ghcr.io/analogj/scrutiny:master-omnibus
        ports:
            - "8088:8080"
            - "8086:8086"
        restart: ${US}
        volumes:
            - ${CONFIG}/scrutiny:/opt/scrutiny/config
            - ${CONFIG}/scrutiny/influxdb2:/opt/scrutiny/influxdb
            - /run/udev:/run/udev:ro

    # Sonarr
    sonarr:
        container_name: sonarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/sonarr:latest
        ports:
            - "8989:8989"
        restart: ${US}
        volumes:
            - ${CONFIG}/sonarr:/config
            - /mnt/vd0/data/videos:/tv
            - /home/${USER}/downloads/qbittorrentvpn:/downloads

    # Tautulli
    tautulli:
        container_name: tautulli
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
        image: tautulli/tautulli:latest
        ports:
            - "8182:8181"
        restart: ${US}
        volumes:
            - ${CONFIG}/tautulli:/config
            - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro

    # Tdarr
    tdarr:
        container_name: tdarr
        devices:
            - "/dev/dri:/dev/dri"
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - serverIP=${IP}
            - serverPort=8266
            - webUIPort=8265
            - internalNode=true
            - nodeID=${SERVER}Node
        image: haveagitgat/tdarr:latest
        ports:
            - "8265:8265"
            - "8266:8266"
            - "8267:8267"
        restart: ${US}
        volumes:
            - ${CONFIG}/tdarr/server:/app/server
            - ${CONFIG}/tdarr/configs:/app/configs
            - ${CONFIG}/tdarr/logs:/app/logs
            - /mnt/vd0/data:/media
            - ${CONFIG}/../../downloads/tdarr/cache:/temp
