#                                            #
# This is my docker compose file for Arnold. #
#                                            #

version: "3.9"

# Services.
services:

    # Esphome
    esphome:
        container_name: esphome
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - USERNAME=${USER}
            - PASSWORD=${PW}
        image: ghcr.io/esphome/esphome:latest
        ports:
            - "6052:6052"
        restart: ${US}
        volumes:
            - ${CONFIG}/esphome:/config
            - /etc/localtime:/etc/localtime:ro

    # Nextcloud
    nextcloud:
        container_name: nextcloud
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
            - MYSQL_PASSWORD=${PW}
            - MYSQL_DATABASE=${NXTCLD_DB_NAME}
            - MYSQL_USER=${NXTCLD_DB_U}
            - MYSQL_HOST=${IP}
            - NEXTCLOUD_ADMIN_USER=${USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${PW}
            - REDIS_HOST=${IP}
        image: linuxserver/nextcloud:latest
        ports:
            - "3333:443"
        restart: ${US}
        volumes:
            - ${CONFIG}/nextcloud:/config
            - /mnt/vd0/data/nextcloud:/data

    # Ouroboros
    ouroboros:
        container_name: ouroboros
        environment:
            - CLEANUP=true
            - CRON=0 4 * * *
            - LOG_LEVEL=info
            - SELF_UPDATE=true
            - NOTIFIERS=${OUROBOROS_NOTIFIERS}
            - TZ=${TZ}
        image: pyouroboros/ouroboros:latest
        restart: ${US}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    # Portainer
    portainer:
        command: -H unix:///var/run/docker.sock
        container_name: portainer
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: portainer/portainer-ce:latest
        ports:
            - "9000:9000"
        restart: ${US}
        volumes:
            - ${CONFIG}/portainer:/data
            - /etc/localtime:/etc/localtime:ro
            - /home/alex/.docker/shared:/shared
            - /var/run/docker.sock:/var/run/docker.sock
