#                                 #
# This is my docker compose file. #
#                                 #

version: "3.9"

# Services.
services:

    # Bitwarden
    bitwarden:
        container_name: bitwarden
        environment:
            - TZ=${TZ}
            - LOG_FILE=/data/bitwarden.log
            - SIGNUPS_ALLOWED=true
        image: bitwardenrs/server:latest
        ports:
            - "8000:80"
        restart: ${US}
        volumes:
            - ${CONFIG}/bitwarden:/data:rw

    # Deluge
    deluge:
        container_name: deluge
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/deluge:latest
        ports:
            - "58846:58846"
            - "58946:58946"
            - "8112:8112"
        restart: ${US}
        volumes:
            - ${CONFIG}/deluge:/config:rw
            - /home/alex/downloads/deluge:/downloads:rw

    # Duplicati
    # duplicati:
    #     container_name: duplicati
    #     environment:
    #         - PUID=${UID}
    #         - PGID=${GID}
    #     image: duplicati/duplicati:latest
    #     ports:
    #         - "8200:8200"
    #     restart: ${US}
    #     volumes:
    #         - ${CONFIG}/duplicati:/duplicati:rw
    #         - /boot:/data-boot:rw
    #         - /etc:/data-etc:rw
    #         - /home:/data-home:rw
    #         - /opt:/data-opt:rw
    #         - /root:/data-root:rw
    #         - /srv:/data-srv:rw
    #         - /usr:/data-usr:rw
    #         - /var:/data-var:rw

    # Factorio
#    factorio:
#        container_name: factorio
#        environment:
#            - PUID=${UID}
#            - PGID=${GID}
#        image: factoriotools/factorio:latest
#        ports:
#            - "34197:34197/udp"
#            - "27015:27015"
#        restart: ${US}
#        volumes:
#            - ${CONFIG}/factorio:/factorio:rw

    # Frigate
    frigate:
        container_name: frigate
        devices:
            # - /dev/bus/usb:/dev/bus/usb # usb coral
            - /dev/dri/renderD128
        environment:
            - TZ=${TZ}
            - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PW}
        image: blakeblackshear/frigate:latest
        ports:
            - "5000:5000"
            - "1935:1935" # RTMP feeds
        privileged: true # this may not be necessary for all setups
        restart: ${US}
        shm_size: "64mb"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIG}/frigate:/config:rw
            - /home/alex/frigate/storage:/media/frigate

    # Gitea
    gitea:
        container_name: gitea
        environment:
            - USER_UID=${UID}
            - USER_GID=${GID}
            - TZ=${TZ}
            - DB_TYPE={GITEA_DB_TYPE}
            - DB_HOST=${GITEA_DB_HOST}
            - DB_NAME=${GITEA_DB_DATABASE}
            - DB_USER=${GITEA_DB_USERNAME}
            - DB_PASSWD=${GITEA_DB_PASSWORD}
        image: gitea/gitea:latest
        ports:
            - "3000:3000"
            - "222:22"
        restart: ${US}
        volumes:
            - ${CONFIG}/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    # Gluetun
    gluetun:
        cap_add:
            - NET_ADMIN
        container_name: gluetun
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - VPNSP=nordvpn
            - OPENVPN_USER=${NORD_USER}
            - OPENVPN_PASSWORD=${NORD_PW}
            - REGION=${NORD_REGION}
            - SERVER_HOSTNAME=${NORD_SERVER}
            - TZ=${TZ}
        image: qmcgaw/gluetun:latest
        ports:
            - "8888:8888/tcp"
            - "8388:8388/tcp"
            - "8388:8388/udp"
            - "6881:6881"
            - "6881:6881/udp"
            - "8113:8113"
        restart: ${US}
        volumes:
            - ${CONFIG}/gluetun:/gluetun:rw

    # Heimdall
    heimdall:
        container_name: heimdall
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/heimdall:latest
        ports:
            - "9009:80"
            - "9010:443"
        restart: ${US}
        volumes:
            - ${CONFIG}/heimdall:/config:rw

    # Jackett
    jackett:
        container_name: jackett
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/jackett:latest
        ports:
            - "9117:9117"
        restart: ${US}
        volumes:
            - ${CONFIG}/jackett:/config:rw
            - /home/alex/downloads/jackett:/downloads:rw
            - /etc/localtime:/etc/localtime:ro

    # Maria DB
    mariadb:
        container_name: mariadb
        environment:
            - TZ=${TZ}
            - MYSQL_ROOT_PASSWORD=nginxproxymanager
            - MYSQL_DATABASE=nginxproxymanager
            - MYSQL_USER=nginxproxymanager
            - MYSQL_PASSWORD=nginxproxymanager
        image: mariadb
        restart: ${US}
        volumes:
            - ${CONFIG}/mariadb/data/mysql:/var/lib/mysql:rw

    # Nginx proxy manager
    nginx-proxy-manager:
        container_name: nginx-proxy-manager
        depends_on: 
            - mariadb
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
        image: jc21/nginx-proxy-manager:latest
        ports:
            - "8181:81"
            - "8080:80"
            - "4443:443"
        restart: ${US}
        volumes:
            - ${CONFIG}/nginx-proxy-manager/config:/app/config:rw
            - ${CONFIG}/nginx-proxy-manager/data:/data:rw
            - ${CONFIG}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt:rw

    # Ouroboros
    ouroboros:
        container_name: ouroboros
        environment:
            - CLEANUP=true
            - CRON=0 4 * * *
            - LOG_LEVEL=info
            - SELF_UPDATE=true
            - IGNORE=mariadb
            - NOTIFIERS=${OUROBOROS_NOTIFIERS}
            - TZ=${TZ}
        image: pyouroboros/ouroboros:latest
        restart: ${US}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    # Plex
    plex:
        container_name: plex
        devices:
            - "/dev/dri:/dev/dri"
        environment:
            - ADVERTISE_IP=http://192.168.1.111:32400/
            - PLEX_UID=${UID}
            - PLEX_GID=${GID}
            - TZ=${TZ}
            - PLEX_CLAIM=${PLEX_CLAIM}
              NVIDIA_DRIVER_CAPIBILITIES=compute,video,utility
            - NVIDIA_VISIBLE_DEVICES=all
        image: plexinc/pms-docker:latest
        ports:
            - "32400:32400"
        restart: ${US}
        volumes:
            - ${CONFIG}/plex:/config:rw
            - /home/alex/downloads/plex/transcode:/transcode:rw
            - /mnt/vd0/data/videos:/data:rw
    
    # Portainer
    portainer:
        command: -H unix:///var/run/docker.sock
        container_name: portainer
        environment:
            - TZ=${TZ}
        image: portainer/portainer-ce:latest
        ports:
            - "9000:9000"
        restart: ${US}
        volumes:
            - ${CONFIG}/portainer:/data:rw
            - /etc/localtime:/etc/localtime:ro
            - /home/alex/.docker/shared:/shared:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw

    # Prowlarr
    prowlarr:
        container_name: prowlarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/prowlarr:develop
        ports:
            - "9696:9696"
        restart: ${US}
        volumes:
            - ${CONFIG}/prowlarr:/config:rw

    # QBittorrent
    qbittorrent:
        container_name: qbittorrent
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
            - WEBUI_PORT=8113
        image: linuxserver/qbittorrent:latest
        network_mode: "service:gluetun"
        restart: ${US}
        volumes:
            - ${CONFIG}/qbittorrent:/config:rw
            - /home/alex/downloads/qbittorrent:/downloads:rw

    # Radarr
    radarr:
        container_name: radarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/radarr:nightly
        ports:
            - "7878:7878"
        restart: ${US}
        volumes:
            - ${CONFIG}/radarr:/config:rw
            - /mnt/vd0/data/videos:/movies:rw
            - /home/alex/downloads/deluge:/downloads:rw

    # Scrutiny
    scrutiny:
        cap_add:
            - SYS_RAWIO
            - SYS_ADMIN
        container_name: scrutiny
        devices:
            - /dev/sda:/dev/sda
            - /dev/sdb:/dev/sdb
            - /dev/sdc:/dev/sdc
            - /dev/sdd:/dev/sdd
            - /dev/sde:/dev/sde
            - /dev/sdf:/dev/sdf
        environment:
            - PGID=${UID}
            - PUID=${GID}
            - TZ=${TZ}
            - SCRUTINY_API_ENDPOINT=http://192.168.1.111:8088
            - SCRUTINY_WEB=true
            - SCRUTINY_COLLECTOR=true
        image: linuxserver/scrutiny
        ports:
            - "8088:8080"
        restart: ${US}
        volumes:
            - /homw/alex/.docker/config/scrutiny:/config
            - /run/udev:/run/udev:ro

    # Sky Factory
    # skyfactory:
    #     container_name: skyfactory
    #     environment:
    #         - PGID=${UID}
    #         - PUID=${GID}
    #         - TZ=${TZ}
    #           #            - SERVER_OP=Niles018
    #     image: cochief/skyfactory4
    #     ports:
    #         - "25566:25565"
    #     restart: ${US}
    #     volumes:
    #         - ${CONFIG}/skyfactory/world:/minecraft/world
    #         - ${CONFIG}/skyfactory/ops.json:/minecraft/ops.json
    #         - ${CONFIG}/skyfactory/server.properties:/minecraft/server.properties
    #         - ${CONFIG}/skyfactory/whitelist.json:/minecraft/whitelist.json

    # Sonarr
    sonarr:
        container_name: sonarr
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=${TZ}
        image: linuxserver/sonarr:latest
        ports:
            - "8989:8989"
        restart: ${US}
        volumes:
            - ${CONFIG}/sonarr:/config:rw
            - /mnt/vd0/data/videos:/tv:rw
            - /home/alex/downloads/deluge:/downloads:rw

    # Tautulli
    tautulli:
        container_name: tautulli
        environment:
            - PUID=${UID}
            - GUID=${GID}
            - TZ=${TZ}
        image: tautulli/tautulli:latest
        ports:
            - "8182:8181"
        restart: ${US}
        volumes:
            - ${CONFIG}/tautulli:/config:rw
            - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
    
    # Tekkit
    # tekkit:
    #     container_name: tekkit
    #     environment:
    #         - PUID=${UID}
    #         - GUID=${GID}
    #         - TZ=${TZ}
    #         - SERVER_OP=Niles018
    #     image: dang1t/tekkit-classic-docker:latest
    #     ports:
    #         - "25565:25565"
    #     restart: ${US}
    #     volumes:
    #         - ${CONFIG}/tekkit-server/world:/minecraft/world
    #         - ${CONFIG}/tekkit-server/world_nether:/minecraft/world_nether
    #         - ${CONFIG}/tekkit-server/world_the_end:/minecraft/world_the_end
    #         - ${CONFIG}/tekkit-server/plugins:/minecraft/plugins
    
    # Valheim
    # valheim-server:
    #     container_name: valheim-server
    #     environment:
    #         - PUID=${UID}
    #         - PGID=${GID}
    #         - TZ=${TZ}
    #         - SERVER_NAME=Kloenkerserver
    #         - WORLD_NAME=Kloenkeraarde
    #         - SERVER_PASS=Kloenker1
    #     image: lloesche/valheim-server
    #     ports:
    #         - "2456-2458:2456-2458/udp"
    #     restart: ${US}
    #     volumes:
    #         - ${CONFIG}/valheim:/config
